// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/protobuf_rpc/net/rpcMsg.proto

#ifndef PROTOBUF_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto__INCLUDED
#define PROTOBUF_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace example {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

class LoginInfo;
class LoginRet;
class chatBroadcast;
class CalRequest;
class CalResponse;
class StatusRequest;
class StatusResponse;
class moveRequest;
class commonResponse;

// ===================================================================

class LoginInfo : public ::google::protobuf::Message {
 public:
  LoginInfo();
  virtual ~LoginInfo();

  LoginInfo(const LoginInfo& from);

  inline LoginInfo& operator=(const LoginInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginInfo& default_instance();

  void Swap(LoginInfo* other);

  // implements Message ----------------------------------------------

  LoginInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginInfo& from);
  void MergeFrom(const LoginInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 roleid = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleidFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // optional int32 roomid = 2;
  inline bool has_roomid() const;
  inline void clear_roomid();
  static const int kRoomidFieldNumber = 2;
  inline ::google::protobuf::int32 roomid() const;
  inline void set_roomid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.LoginInfo)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_roomid();
  inline void clear_has_roomid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 roomid_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static LoginInfo* default_instance_;
};
// -------------------------------------------------------------------

class LoginRet : public ::google::protobuf::Message {
 public:
  LoginRet();
  virtual ~LoginRet();

  LoginRet(const LoginRet& from);

  inline LoginRet& operator=(const LoginRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRet& default_instance();

  void Swap(LoginRet* other);

  // implements Message ----------------------------------------------

  LoginRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRet& from);
  void MergeFrom(const LoginRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.LoginRet)
 private:
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static LoginRet* default_instance_;
};
// -------------------------------------------------------------------

class chatBroadcast : public ::google::protobuf::Message {
 public:
  chatBroadcast();
  virtual ~chatBroadcast();

  chatBroadcast(const chatBroadcast& from);

  inline chatBroadcast& operator=(const chatBroadcast& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const chatBroadcast& default_instance();

  void Swap(chatBroadcast* other);

  // implements Message ----------------------------------------------

  chatBroadcast* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const chatBroadcast& from);
  void MergeFrom(const chatBroadcast& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string said = 1;
  inline bool has_said() const;
  inline void clear_said();
  static const int kSaidFieldNumber = 1;
  inline const ::std::string& said() const;
  inline void set_said(const ::std::string& value);
  inline void set_said(const char* value);
  inline void set_said(const char* value, size_t size);
  inline ::std::string* mutable_said();
  inline ::std::string* release_said();
  inline void set_allocated_said(::std::string* said);

  // @@protoc_insertion_point(class_scope:example.chatBroadcast)
 private:
  inline void set_has_said();
  inline void clear_has_said();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* said_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static chatBroadcast* default_instance_;
};
// -------------------------------------------------------------------

class CalRequest : public ::google::protobuf::Message {
 public:
  CalRequest();
  virtual ~CalRequest();

  CalRequest(const CalRequest& from);

  inline CalRequest& operator=(const CalRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalRequest& default_instance();

  void Swap(CalRequest* other);

  // implements Message ----------------------------------------------

  CalRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalRequest& from);
  void MergeFrom(const CalRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 a = 1;
  inline bool has_a() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline ::google::protobuf::int32 a() const;
  inline void set_a(::google::protobuf::int32 value);

  // optional int32 b = 2;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 2;
  inline ::google::protobuf::int32 b() const;
  inline void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.CalRequest)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_b();
  inline void clear_has_b();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static CalRequest* default_instance_;
};
// -------------------------------------------------------------------

class CalResponse : public ::google::protobuf::Message {
 public:
  CalResponse();
  virtual ~CalResponse();

  CalResponse(const CalResponse& from);

  inline CalResponse& operator=(const CalResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalResponse& default_instance();

  void Swap(CalResponse* other);

  // implements Message ----------------------------------------------

  CalResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalResponse& from);
  void MergeFrom(const CalResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 c = 1;
  inline bool has_c() const;
  inline void clear_c();
  static const int kCFieldNumber = 1;
  inline ::google::protobuf::int32 c() const;
  inline void set_c(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.CalResponse)
 private:
  inline void set_has_c();
  inline void clear_has_c();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 c_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static CalResponse* default_instance_;
};
// -------------------------------------------------------------------

class StatusRequest : public ::google::protobuf::Message {
 public:
  StatusRequest();
  virtual ~StatusRequest();

  StatusRequest(const StatusRequest& from);

  inline StatusRequest& operator=(const StatusRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusRequest& default_instance();

  void Swap(StatusRequest* other);

  // implements Message ----------------------------------------------

  StatusRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StatusRequest& from);
  void MergeFrom(const StatusRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 cmd = 1;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 1;
  inline ::google::protobuf::int32 cmd() const;
  inline void set_cmd(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.StatusRequest)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 cmd_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static StatusRequest* default_instance_;
};
// -------------------------------------------------------------------

class StatusResponse : public ::google::protobuf::Message {
 public:
  StatusResponse();
  virtual ~StatusResponse();

  StatusResponse(const StatusResponse& from);

  inline StatusResponse& operator=(const StatusResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusResponse& default_instance();

  void Swap(StatusResponse* other);

  // implements Message ----------------------------------------------

  StatusResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StatusResponse& from);
  void MergeFrom(const StatusResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.StatusResponse)
 private:
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static StatusResponse* default_instance_;
};
// -------------------------------------------------------------------

class moveRequest : public ::google::protobuf::Message {
 public:
  moveRequest();
  virtual ~moveRequest();

  moveRequest(const moveRequest& from);

  inline moveRequest& operator=(const moveRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const moveRequest& default_instance();

  void Swap(moveRequest* other);

  // implements Message ----------------------------------------------

  moveRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const moveRequest& from);
  void MergeFrom(const moveRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 direction = 1;
  inline bool has_direction() const;
  inline void clear_direction();
  static const int kDirectionFieldNumber = 1;
  inline ::google::protobuf::int32 direction() const;
  inline void set_direction(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.moveRequest)
 private:
  inline void set_has_direction();
  inline void clear_has_direction();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 direction_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static moveRequest* default_instance_;
};
// -------------------------------------------------------------------

class commonResponse : public ::google::protobuf::Message {
 public:
  commonResponse();
  virtual ~commonResponse();

  commonResponse(const commonResponse& from);

  inline commonResponse& operator=(const commonResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const commonResponse& default_instance();

  void Swap(commonResponse* other);

  // implements Message ----------------------------------------------

  commonResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const commonResponse& from);
  void MergeFrom(const commonResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.commonResponse)
 private:
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static commonResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// LoginInfo

// optional int32 roleid = 1;
inline bool LoginInfo::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginInfo::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginInfo::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginInfo::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 LoginInfo::roleid() const {
  // @@protoc_insertion_point(field_get:example.LoginInfo.roleid)
  return roleid_;
}
inline void LoginInfo::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
  // @@protoc_insertion_point(field_set:example.LoginInfo.roleid)
}

// optional int32 roomid = 2;
inline bool LoginInfo::has_roomid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginInfo::set_has_roomid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginInfo::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginInfo::clear_roomid() {
  roomid_ = 0;
  clear_has_roomid();
}
inline ::google::protobuf::int32 LoginInfo::roomid() const {
  // @@protoc_insertion_point(field_get:example.LoginInfo.roomid)
  return roomid_;
}
inline void LoginInfo::set_roomid(::google::protobuf::int32 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:example.LoginInfo.roomid)
}

// -------------------------------------------------------------------

// LoginRet

// optional int32 status = 1;
inline bool LoginRet::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRet::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRet::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRet::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 LoginRet::status() const {
  // @@protoc_insertion_point(field_get:example.LoginRet.status)
  return status_;
}
inline void LoginRet::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:example.LoginRet.status)
}

// -------------------------------------------------------------------

// chatBroadcast

// optional string said = 1;
inline bool chatBroadcast::has_said() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void chatBroadcast::set_has_said() {
  _has_bits_[0] |= 0x00000001u;
}
inline void chatBroadcast::clear_has_said() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void chatBroadcast::clear_said() {
  if (said_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_->clear();
  }
  clear_has_said();
}
inline const ::std::string& chatBroadcast::said() const {
  // @@protoc_insertion_point(field_get:example.chatBroadcast.said)
  return *said_;
}
inline void chatBroadcast::set_said(const ::std::string& value) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(value);
  // @@protoc_insertion_point(field_set:example.chatBroadcast.said)
}
inline void chatBroadcast::set_said(const char* value) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(value);
  // @@protoc_insertion_point(field_set_char:example.chatBroadcast.said)
}
inline void chatBroadcast::set_said(const char* value, size_t size) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:example.chatBroadcast.said)
}
inline ::std::string* chatBroadcast::mutable_said() {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:example.chatBroadcast.said)
  return said_;
}
inline ::std::string* chatBroadcast::release_said() {
  clear_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = said_;
    said_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void chatBroadcast::set_allocated_said(::std::string* said) {
  if (said_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete said_;
  }
  if (said) {
    set_has_said();
    said_ = said;
  } else {
    clear_has_said();
    said_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:example.chatBroadcast.said)
}

// -------------------------------------------------------------------

// CalRequest

// optional int32 a = 1;
inline bool CalRequest::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CalRequest::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CalRequest::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CalRequest::clear_a() {
  a_ = 0;
  clear_has_a();
}
inline ::google::protobuf::int32 CalRequest::a() const {
  // @@protoc_insertion_point(field_get:example.CalRequest.a)
  return a_;
}
inline void CalRequest::set_a(::google::protobuf::int32 value) {
  set_has_a();
  a_ = value;
  // @@protoc_insertion_point(field_set:example.CalRequest.a)
}

// optional int32 b = 2;
inline bool CalRequest::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CalRequest::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CalRequest::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CalRequest::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 CalRequest::b() const {
  // @@protoc_insertion_point(field_get:example.CalRequest.b)
  return b_;
}
inline void CalRequest::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:example.CalRequest.b)
}

// -------------------------------------------------------------------

// CalResponse

// optional int32 c = 1;
inline bool CalResponse::has_c() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CalResponse::set_has_c() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CalResponse::clear_has_c() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CalResponse::clear_c() {
  c_ = 0;
  clear_has_c();
}
inline ::google::protobuf::int32 CalResponse::c() const {
  // @@protoc_insertion_point(field_get:example.CalResponse.c)
  return c_;
}
inline void CalResponse::set_c(::google::protobuf::int32 value) {
  set_has_c();
  c_ = value;
  // @@protoc_insertion_point(field_set:example.CalResponse.c)
}

// -------------------------------------------------------------------

// StatusRequest

// optional int32 cmd = 1;
inline bool StatusRequest::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StatusRequest::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StatusRequest::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StatusRequest::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 StatusRequest::cmd() const {
  // @@protoc_insertion_point(field_get:example.StatusRequest.cmd)
  return cmd_;
}
inline void StatusRequest::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:example.StatusRequest.cmd)
}

// -------------------------------------------------------------------

// StatusResponse

// optional int32 status = 1;
inline bool StatusResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StatusResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StatusResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StatusResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 StatusResponse::status() const {
  // @@protoc_insertion_point(field_get:example.StatusResponse.status)
  return status_;
}
inline void StatusResponse::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:example.StatusResponse.status)
}

// -------------------------------------------------------------------

// moveRequest

// optional int32 direction = 1;
inline bool moveRequest::has_direction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void moveRequest::set_has_direction() {
  _has_bits_[0] |= 0x00000001u;
}
inline void moveRequest::clear_has_direction() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void moveRequest::clear_direction() {
  direction_ = 0;
  clear_has_direction();
}
inline ::google::protobuf::int32 moveRequest::direction() const {
  // @@protoc_insertion_point(field_get:example.moveRequest.direction)
  return direction_;
}
inline void moveRequest::set_direction(::google::protobuf::int32 value) {
  set_has_direction();
  direction_ = value;
  // @@protoc_insertion_point(field_set:example.moveRequest.direction)
}

// -------------------------------------------------------------------

// commonResponse

// optional int32 status = 1;
inline bool commonResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void commonResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void commonResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void commonResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 commonResponse::status() const {
  // @@protoc_insertion_point(field_get:example.commonResponse.status)
  return status_;
}
inline void commonResponse::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:example.commonResponse.status)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace example

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto__INCLUDED
