// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/protobuf_rpc/net/rpcMsg.proto

#ifndef PROTOBUF_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto__INCLUDED
#define PROTOBUF_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace example {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

class baseInfo;
class LoginInfo;
class playersInfo;
class chatReceive;
class chatBroadcast;
class CalRequest;
class CalResponse;
class StatusReceive;
class statusBroadcast;
class moveRequest;
class moveBroadcast;
class commonResponse;

// ===================================================================

class baseInfo : public ::google::protobuf::Message {
 public:
  baseInfo();
  virtual ~baseInfo();

  baseInfo(const baseInfo& from);

  inline baseInfo& operator=(const baseInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const baseInfo& default_instance();

  void Swap(baseInfo* other);

  // implements Message ----------------------------------------------

  baseInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const baseInfo& from);
  void MergeFrom(const baseInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 roleid = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleidFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional int32 status = 3;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 3;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.baseInfo)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static baseInfo* default_instance_;
};
// -------------------------------------------------------------------

class LoginInfo : public ::google::protobuf::Message {
 public:
  LoginInfo();
  virtual ~LoginInfo();

  LoginInfo(const LoginInfo& from);

  inline LoginInfo& operator=(const LoginInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginInfo& default_instance();

  void Swap(LoginInfo* other);

  // implements Message ----------------------------------------------

  LoginInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginInfo& from);
  void MergeFrom(const LoginInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 roleid = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleidFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // optional int32 roomid = 2;
  inline bool has_roomid() const;
  inline void clear_roomid();
  static const int kRoomidFieldNumber = 2;
  inline ::google::protobuf::int32 roomid() const;
  inline void set_roomid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.LoginInfo)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_roomid();
  inline void clear_has_roomid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 roomid_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static LoginInfo* default_instance_;
};
// -------------------------------------------------------------------

class playersInfo : public ::google::protobuf::Message {
 public:
  playersInfo();
  virtual ~playersInfo();

  playersInfo(const playersInfo& from);

  inline playersInfo& operator=(const playersInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const playersInfo& default_instance();

  void Swap(playersInfo* other);

  // implements Message ----------------------------------------------

  playersInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const playersInfo& from);
  void MergeFrom(const playersInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .example.commonResponse cr = 1;
  inline bool has_cr() const;
  inline void clear_cr();
  static const int kCrFieldNumber = 1;
  inline const ::example::commonResponse& cr() const;
  inline ::example::commonResponse* mutable_cr();
  inline ::example::commonResponse* release_cr();
  inline void set_allocated_cr(::example::commonResponse* cr);

  // optional int32 roomHolder = 2;
  inline bool has_roomholder() const;
  inline void clear_roomholder();
  static const int kRoomHolderFieldNumber = 2;
  inline ::google::protobuf::int32 roomholder() const;
  inline void set_roomholder(::google::protobuf::int32 value);

  // repeated .example.baseInfo baseInfos = 3;
  inline int baseinfos_size() const;
  inline void clear_baseinfos();
  static const int kBaseInfosFieldNumber = 3;
  inline const ::example::baseInfo& baseinfos(int index) const;
  inline ::example::baseInfo* mutable_baseinfos(int index);
  inline ::example::baseInfo* add_baseinfos();
  inline const ::google::protobuf::RepeatedPtrField< ::example::baseInfo >&
      baseinfos() const;
  inline ::google::protobuf::RepeatedPtrField< ::example::baseInfo >*
      mutable_baseinfos();

  // @@protoc_insertion_point(class_scope:example.playersInfo)
 private:
  inline void set_has_cr();
  inline void clear_has_cr();
  inline void set_has_roomholder();
  inline void clear_has_roomholder();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::example::commonResponse* cr_;
  ::google::protobuf::RepeatedPtrField< ::example::baseInfo > baseinfos_;
  ::google::protobuf::int32 roomholder_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static playersInfo* default_instance_;
};
// -------------------------------------------------------------------

class chatReceive : public ::google::protobuf::Message {
 public:
  chatReceive();
  virtual ~chatReceive();

  chatReceive(const chatReceive& from);

  inline chatReceive& operator=(const chatReceive& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const chatReceive& default_instance();

  void Swap(chatReceive* other);

  // implements Message ----------------------------------------------

  chatReceive* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const chatReceive& from);
  void MergeFrom(const chatReceive& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string said = 1;
  inline bool has_said() const;
  inline void clear_said();
  static const int kSaidFieldNumber = 1;
  inline const ::std::string& said() const;
  inline void set_said(const ::std::string& value);
  inline void set_said(const char* value);
  inline void set_said(const char* value, size_t size);
  inline ::std::string* mutable_said();
  inline ::std::string* release_said();
  inline void set_allocated_said(::std::string* said);

  // @@protoc_insertion_point(class_scope:example.chatReceive)
 private:
  inline void set_has_said();
  inline void clear_has_said();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* said_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static chatReceive* default_instance_;
};
// -------------------------------------------------------------------

class chatBroadcast : public ::google::protobuf::Message {
 public:
  chatBroadcast();
  virtual ~chatBroadcast();

  chatBroadcast(const chatBroadcast& from);

  inline chatBroadcast& operator=(const chatBroadcast& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const chatBroadcast& default_instance();

  void Swap(chatBroadcast* other);

  // implements Message ----------------------------------------------

  chatBroadcast* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const chatBroadcast& from);
  void MergeFrom(const chatBroadcast& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 roleID = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // optional string said = 2;
  inline bool has_said() const;
  inline void clear_said();
  static const int kSaidFieldNumber = 2;
  inline const ::std::string& said() const;
  inline void set_said(const ::std::string& value);
  inline void set_said(const char* value);
  inline void set_said(const char* value, size_t size);
  inline ::std::string* mutable_said();
  inline ::std::string* release_said();
  inline void set_allocated_said(::std::string* said);

  // @@protoc_insertion_point(class_scope:example.chatBroadcast)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_said();
  inline void clear_has_said();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* said_;
  ::google::protobuf::int32 roleid_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static chatBroadcast* default_instance_;
};
// -------------------------------------------------------------------

class CalRequest : public ::google::protobuf::Message {
 public:
  CalRequest();
  virtual ~CalRequest();

  CalRequest(const CalRequest& from);

  inline CalRequest& operator=(const CalRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalRequest& default_instance();

  void Swap(CalRequest* other);

  // implements Message ----------------------------------------------

  CalRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalRequest& from);
  void MergeFrom(const CalRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 a = 1;
  inline bool has_a() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline ::google::protobuf::int32 a() const;
  inline void set_a(::google::protobuf::int32 value);

  // optional int32 b = 2;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 2;
  inline ::google::protobuf::int32 b() const;
  inline void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.CalRequest)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_b();
  inline void clear_has_b();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static CalRequest* default_instance_;
};
// -------------------------------------------------------------------

class CalResponse : public ::google::protobuf::Message {
 public:
  CalResponse();
  virtual ~CalResponse();

  CalResponse(const CalResponse& from);

  inline CalResponse& operator=(const CalResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalResponse& default_instance();

  void Swap(CalResponse* other);

  // implements Message ----------------------------------------------

  CalResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalResponse& from);
  void MergeFrom(const CalResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 c = 1;
  inline bool has_c() const;
  inline void clear_c();
  static const int kCFieldNumber = 1;
  inline ::google::protobuf::int32 c() const;
  inline void set_c(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.CalResponse)
 private:
  inline void set_has_c();
  inline void clear_has_c();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 c_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static CalResponse* default_instance_;
};
// -------------------------------------------------------------------

class StatusReceive : public ::google::protobuf::Message {
 public:
  StatusReceive();
  virtual ~StatusReceive();

  StatusReceive(const StatusReceive& from);

  inline StatusReceive& operator=(const StatusReceive& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusReceive& default_instance();

  void Swap(StatusReceive* other);

  // implements Message ----------------------------------------------

  StatusReceive* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StatusReceive& from);
  void MergeFrom(const StatusReceive& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 cmd = 1;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 1;
  inline ::google::protobuf::int32 cmd() const;
  inline void set_cmd(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.StatusReceive)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 cmd_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static StatusReceive* default_instance_;
};
// -------------------------------------------------------------------

class statusBroadcast : public ::google::protobuf::Message {
 public:
  statusBroadcast();
  virtual ~statusBroadcast();

  statusBroadcast(const statusBroadcast& from);

  inline statusBroadcast& operator=(const statusBroadcast& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const statusBroadcast& default_instance();

  void Swap(statusBroadcast* other);

  // implements Message ----------------------------------------------

  statusBroadcast* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const statusBroadcast& from);
  void MergeFrom(const statusBroadcast& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 roleID = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // optional int32 cmd = 2;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 2;
  inline ::google::protobuf::int32 cmd() const;
  inline void set_cmd(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.statusBroadcast)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_cmd();
  inline void clear_has_cmd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 cmd_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static statusBroadcast* default_instance_;
};
// -------------------------------------------------------------------

class moveRequest : public ::google::protobuf::Message {
 public:
  moveRequest();
  virtual ~moveRequest();

  moveRequest(const moveRequest& from);

  inline moveRequest& operator=(const moveRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const moveRequest& default_instance();

  void Swap(moveRequest* other);

  // implements Message ----------------------------------------------

  moveRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const moveRequest& from);
  void MergeFrom(const moveRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 direction = 1;
  inline bool has_direction() const;
  inline void clear_direction();
  static const int kDirectionFieldNumber = 1;
  inline ::google::protobuf::int32 direction() const;
  inline void set_direction(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.moveRequest)
 private:
  inline void set_has_direction();
  inline void clear_has_direction();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 direction_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static moveRequest* default_instance_;
};
// -------------------------------------------------------------------

class moveBroadcast : public ::google::protobuf::Message {
 public:
  moveBroadcast();
  virtual ~moveBroadcast();

  moveBroadcast(const moveBroadcast& from);

  inline moveBroadcast& operator=(const moveBroadcast& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const moveBroadcast& default_instance();

  void Swap(moveBroadcast* other);

  // implements Message ----------------------------------------------

  moveBroadcast* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const moveBroadcast& from);
  void MergeFrom(const moveBroadcast& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 roleID = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // optional int32 cmd = 2;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 2;
  inline ::google::protobuf::int32 cmd() const;
  inline void set_cmd(::google::protobuf::int32 value);

  // optional int32 roomID = 3;
  inline bool has_roomid() const;
  inline void clear_roomid();
  static const int kRoomIDFieldNumber = 3;
  inline ::google::protobuf::int32 roomid() const;
  inline void set_roomid(::google::protobuf::int32 value);

  // optional int32 cardID = 4;
  inline bool has_cardid() const;
  inline void clear_cardid();
  static const int kCardIDFieldNumber = 4;
  inline ::google::protobuf::int32 cardid() const;
  inline void set_cardid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.moveBroadcast)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_cmd();
  inline void clear_has_cmd();
  inline void set_has_roomid();
  inline void clear_has_roomid();
  inline void set_has_cardid();
  inline void clear_has_cardid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 cmd_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 cardid_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static moveBroadcast* default_instance_;
};
// -------------------------------------------------------------------

class commonResponse : public ::google::protobuf::Message {
 public:
  commonResponse();
  virtual ~commonResponse();

  commonResponse(const commonResponse& from);

  inline commonResponse& operator=(const commonResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const commonResponse& default_instance();

  void Swap(commonResponse* other);

  // implements Message ----------------------------------------------

  commonResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const commonResponse& from);
  void MergeFrom(const commonResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:example.commonResponse)
 private:
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_AssignDesc_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();
  friend void protobuf_ShutdownFile_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto();

  void InitAsDefaultInstance();
  static commonResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// baseInfo

// optional int32 roleid = 1;
inline bool baseInfo::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void baseInfo::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void baseInfo::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void baseInfo::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 baseInfo::roleid() const {
  // @@protoc_insertion_point(field_get:example.baseInfo.roleid)
  return roleid_;
}
inline void baseInfo::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
  // @@protoc_insertion_point(field_set:example.baseInfo.roleid)
}

// optional string name = 2;
inline bool baseInfo::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void baseInfo::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void baseInfo::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void baseInfo::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& baseInfo::name() const {
  // @@protoc_insertion_point(field_get:example.baseInfo.name)
  return *name_;
}
inline void baseInfo::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:example.baseInfo.name)
}
inline void baseInfo::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:example.baseInfo.name)
}
inline void baseInfo::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:example.baseInfo.name)
}
inline ::std::string* baseInfo::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:example.baseInfo.name)
  return name_;
}
inline ::std::string* baseInfo::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void baseInfo::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:example.baseInfo.name)
}

// optional int32 status = 3;
inline bool baseInfo::has_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void baseInfo::set_has_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void baseInfo::clear_has_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void baseInfo::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 baseInfo::status() const {
  // @@protoc_insertion_point(field_get:example.baseInfo.status)
  return status_;
}
inline void baseInfo::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:example.baseInfo.status)
}

// -------------------------------------------------------------------

// LoginInfo

// optional int32 roleid = 1;
inline bool LoginInfo::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginInfo::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginInfo::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginInfo::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 LoginInfo::roleid() const {
  // @@protoc_insertion_point(field_get:example.LoginInfo.roleid)
  return roleid_;
}
inline void LoginInfo::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
  // @@protoc_insertion_point(field_set:example.LoginInfo.roleid)
}

// optional int32 roomid = 2;
inline bool LoginInfo::has_roomid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginInfo::set_has_roomid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginInfo::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginInfo::clear_roomid() {
  roomid_ = 0;
  clear_has_roomid();
}
inline ::google::protobuf::int32 LoginInfo::roomid() const {
  // @@protoc_insertion_point(field_get:example.LoginInfo.roomid)
  return roomid_;
}
inline void LoginInfo::set_roomid(::google::protobuf::int32 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:example.LoginInfo.roomid)
}

// -------------------------------------------------------------------

// playersInfo

// optional .example.commonResponse cr = 1;
inline bool playersInfo::has_cr() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void playersInfo::set_has_cr() {
  _has_bits_[0] |= 0x00000001u;
}
inline void playersInfo::clear_has_cr() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void playersInfo::clear_cr() {
  if (cr_ != NULL) cr_->::example::commonResponse::Clear();
  clear_has_cr();
}
inline const ::example::commonResponse& playersInfo::cr() const {
  // @@protoc_insertion_point(field_get:example.playersInfo.cr)
  return cr_ != NULL ? *cr_ : *default_instance_->cr_;
}
inline ::example::commonResponse* playersInfo::mutable_cr() {
  set_has_cr();
  if (cr_ == NULL) cr_ = new ::example::commonResponse;
  // @@protoc_insertion_point(field_mutable:example.playersInfo.cr)
  return cr_;
}
inline ::example::commonResponse* playersInfo::release_cr() {
  clear_has_cr();
  ::example::commonResponse* temp = cr_;
  cr_ = NULL;
  return temp;
}
inline void playersInfo::set_allocated_cr(::example::commonResponse* cr) {
  delete cr_;
  cr_ = cr;
  if (cr) {
    set_has_cr();
  } else {
    clear_has_cr();
  }
  // @@protoc_insertion_point(field_set_allocated:example.playersInfo.cr)
}

// optional int32 roomHolder = 2;
inline bool playersInfo::has_roomholder() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void playersInfo::set_has_roomholder() {
  _has_bits_[0] |= 0x00000002u;
}
inline void playersInfo::clear_has_roomholder() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void playersInfo::clear_roomholder() {
  roomholder_ = 0;
  clear_has_roomholder();
}
inline ::google::protobuf::int32 playersInfo::roomholder() const {
  // @@protoc_insertion_point(field_get:example.playersInfo.roomHolder)
  return roomholder_;
}
inline void playersInfo::set_roomholder(::google::protobuf::int32 value) {
  set_has_roomholder();
  roomholder_ = value;
  // @@protoc_insertion_point(field_set:example.playersInfo.roomHolder)
}

// repeated .example.baseInfo baseInfos = 3;
inline int playersInfo::baseinfos_size() const {
  return baseinfos_.size();
}
inline void playersInfo::clear_baseinfos() {
  baseinfos_.Clear();
}
inline const ::example::baseInfo& playersInfo::baseinfos(int index) const {
  // @@protoc_insertion_point(field_get:example.playersInfo.baseInfos)
  return baseinfos_.Get(index);
}
inline ::example::baseInfo* playersInfo::mutable_baseinfos(int index) {
  // @@protoc_insertion_point(field_mutable:example.playersInfo.baseInfos)
  return baseinfos_.Mutable(index);
}
inline ::example::baseInfo* playersInfo::add_baseinfos() {
  // @@protoc_insertion_point(field_add:example.playersInfo.baseInfos)
  return baseinfos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::example::baseInfo >&
playersInfo::baseinfos() const {
  // @@protoc_insertion_point(field_list:example.playersInfo.baseInfos)
  return baseinfos_;
}
inline ::google::protobuf::RepeatedPtrField< ::example::baseInfo >*
playersInfo::mutable_baseinfos() {
  // @@protoc_insertion_point(field_mutable_list:example.playersInfo.baseInfos)
  return &baseinfos_;
}

// -------------------------------------------------------------------

// chatReceive

// optional string said = 1;
inline bool chatReceive::has_said() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void chatReceive::set_has_said() {
  _has_bits_[0] |= 0x00000001u;
}
inline void chatReceive::clear_has_said() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void chatReceive::clear_said() {
  if (said_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_->clear();
  }
  clear_has_said();
}
inline const ::std::string& chatReceive::said() const {
  // @@protoc_insertion_point(field_get:example.chatReceive.said)
  return *said_;
}
inline void chatReceive::set_said(const ::std::string& value) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(value);
  // @@protoc_insertion_point(field_set:example.chatReceive.said)
}
inline void chatReceive::set_said(const char* value) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(value);
  // @@protoc_insertion_point(field_set_char:example.chatReceive.said)
}
inline void chatReceive::set_said(const char* value, size_t size) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:example.chatReceive.said)
}
inline ::std::string* chatReceive::mutable_said() {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:example.chatReceive.said)
  return said_;
}
inline ::std::string* chatReceive::release_said() {
  clear_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = said_;
    said_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void chatReceive::set_allocated_said(::std::string* said) {
  if (said_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete said_;
  }
  if (said) {
    set_has_said();
    said_ = said;
  } else {
    clear_has_said();
    said_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:example.chatReceive.said)
}

// -------------------------------------------------------------------

// chatBroadcast

// optional int32 roleID = 1;
inline bool chatBroadcast::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void chatBroadcast::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void chatBroadcast::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void chatBroadcast::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 chatBroadcast::roleid() const {
  // @@protoc_insertion_point(field_get:example.chatBroadcast.roleID)
  return roleid_;
}
inline void chatBroadcast::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
  // @@protoc_insertion_point(field_set:example.chatBroadcast.roleID)
}

// optional string said = 2;
inline bool chatBroadcast::has_said() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void chatBroadcast::set_has_said() {
  _has_bits_[0] |= 0x00000002u;
}
inline void chatBroadcast::clear_has_said() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void chatBroadcast::clear_said() {
  if (said_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_->clear();
  }
  clear_has_said();
}
inline const ::std::string& chatBroadcast::said() const {
  // @@protoc_insertion_point(field_get:example.chatBroadcast.said)
  return *said_;
}
inline void chatBroadcast::set_said(const ::std::string& value) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(value);
  // @@protoc_insertion_point(field_set:example.chatBroadcast.said)
}
inline void chatBroadcast::set_said(const char* value) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(value);
  // @@protoc_insertion_point(field_set_char:example.chatBroadcast.said)
}
inline void chatBroadcast::set_said(const char* value, size_t size) {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  said_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:example.chatBroadcast.said)
}
inline ::std::string* chatBroadcast::mutable_said() {
  set_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    said_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:example.chatBroadcast.said)
  return said_;
}
inline ::std::string* chatBroadcast::release_said() {
  clear_has_said();
  if (said_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = said_;
    said_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void chatBroadcast::set_allocated_said(::std::string* said) {
  if (said_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete said_;
  }
  if (said) {
    set_has_said();
    said_ = said;
  } else {
    clear_has_said();
    said_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:example.chatBroadcast.said)
}

// -------------------------------------------------------------------

// CalRequest

// optional int32 a = 1;
inline bool CalRequest::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CalRequest::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CalRequest::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CalRequest::clear_a() {
  a_ = 0;
  clear_has_a();
}
inline ::google::protobuf::int32 CalRequest::a() const {
  // @@protoc_insertion_point(field_get:example.CalRequest.a)
  return a_;
}
inline void CalRequest::set_a(::google::protobuf::int32 value) {
  set_has_a();
  a_ = value;
  // @@protoc_insertion_point(field_set:example.CalRequest.a)
}

// optional int32 b = 2;
inline bool CalRequest::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CalRequest::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CalRequest::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CalRequest::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 CalRequest::b() const {
  // @@protoc_insertion_point(field_get:example.CalRequest.b)
  return b_;
}
inline void CalRequest::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:example.CalRequest.b)
}

// -------------------------------------------------------------------

// CalResponse

// optional int32 c = 1;
inline bool CalResponse::has_c() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CalResponse::set_has_c() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CalResponse::clear_has_c() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CalResponse::clear_c() {
  c_ = 0;
  clear_has_c();
}
inline ::google::protobuf::int32 CalResponse::c() const {
  // @@protoc_insertion_point(field_get:example.CalResponse.c)
  return c_;
}
inline void CalResponse::set_c(::google::protobuf::int32 value) {
  set_has_c();
  c_ = value;
  // @@protoc_insertion_point(field_set:example.CalResponse.c)
}

// -------------------------------------------------------------------

// StatusReceive

// optional int32 cmd = 1;
inline bool StatusReceive::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StatusReceive::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StatusReceive::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StatusReceive::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 StatusReceive::cmd() const {
  // @@protoc_insertion_point(field_get:example.StatusReceive.cmd)
  return cmd_;
}
inline void StatusReceive::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:example.StatusReceive.cmd)
}

// -------------------------------------------------------------------

// statusBroadcast

// optional int32 roleID = 1;
inline bool statusBroadcast::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void statusBroadcast::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void statusBroadcast::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void statusBroadcast::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 statusBroadcast::roleid() const {
  // @@protoc_insertion_point(field_get:example.statusBroadcast.roleID)
  return roleid_;
}
inline void statusBroadcast::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
  // @@protoc_insertion_point(field_set:example.statusBroadcast.roleID)
}

// optional int32 cmd = 2;
inline bool statusBroadcast::has_cmd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void statusBroadcast::set_has_cmd() {
  _has_bits_[0] |= 0x00000002u;
}
inline void statusBroadcast::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void statusBroadcast::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 statusBroadcast::cmd() const {
  // @@protoc_insertion_point(field_get:example.statusBroadcast.cmd)
  return cmd_;
}
inline void statusBroadcast::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:example.statusBroadcast.cmd)
}

// -------------------------------------------------------------------

// moveRequest

// optional int32 direction = 1;
inline bool moveRequest::has_direction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void moveRequest::set_has_direction() {
  _has_bits_[0] |= 0x00000001u;
}
inline void moveRequest::clear_has_direction() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void moveRequest::clear_direction() {
  direction_ = 0;
  clear_has_direction();
}
inline ::google::protobuf::int32 moveRequest::direction() const {
  // @@protoc_insertion_point(field_get:example.moveRequest.direction)
  return direction_;
}
inline void moveRequest::set_direction(::google::protobuf::int32 value) {
  set_has_direction();
  direction_ = value;
  // @@protoc_insertion_point(field_set:example.moveRequest.direction)
}

// -------------------------------------------------------------------

// moveBroadcast

// optional int32 roleID = 1;
inline bool moveBroadcast::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void moveBroadcast::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void moveBroadcast::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void moveBroadcast::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 moveBroadcast::roleid() const {
  // @@protoc_insertion_point(field_get:example.moveBroadcast.roleID)
  return roleid_;
}
inline void moveBroadcast::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
  // @@protoc_insertion_point(field_set:example.moveBroadcast.roleID)
}

// optional int32 cmd = 2;
inline bool moveBroadcast::has_cmd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void moveBroadcast::set_has_cmd() {
  _has_bits_[0] |= 0x00000002u;
}
inline void moveBroadcast::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void moveBroadcast::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 moveBroadcast::cmd() const {
  // @@protoc_insertion_point(field_get:example.moveBroadcast.cmd)
  return cmd_;
}
inline void moveBroadcast::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:example.moveBroadcast.cmd)
}

// optional int32 roomID = 3;
inline bool moveBroadcast::has_roomid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void moveBroadcast::set_has_roomid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void moveBroadcast::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void moveBroadcast::clear_roomid() {
  roomid_ = 0;
  clear_has_roomid();
}
inline ::google::protobuf::int32 moveBroadcast::roomid() const {
  // @@protoc_insertion_point(field_get:example.moveBroadcast.roomID)
  return roomid_;
}
inline void moveBroadcast::set_roomid(::google::protobuf::int32 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:example.moveBroadcast.roomID)
}

// optional int32 cardID = 4;
inline bool moveBroadcast::has_cardid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void moveBroadcast::set_has_cardid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void moveBroadcast::clear_has_cardid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void moveBroadcast::clear_cardid() {
  cardid_ = 0;
  clear_has_cardid();
}
inline ::google::protobuf::int32 moveBroadcast::cardid() const {
  // @@protoc_insertion_point(field_get:example.moveBroadcast.cardID)
  return cardid_;
}
inline void moveBroadcast::set_cardid(::google::protobuf::int32 value) {
  set_has_cardid();
  cardid_ = value;
  // @@protoc_insertion_point(field_set:example.moveBroadcast.cardID)
}

// -------------------------------------------------------------------

// commonResponse

// optional int32 status = 1;
inline bool commonResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void commonResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void commonResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void commonResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 commonResponse::status() const {
  // @@protoc_insertion_point(field_get:example.commonResponse.status)
  return status_;
}
inline void commonResponse::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:example.commonResponse.status)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace example

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_example_2fprotobuf_5frpc_2fnet_2frpcMsg_2eproto__INCLUDED
